### ISSUE TITLE
Thanksgiving 🐓 

### ISSUE THREAD

**Issue by samzhang111** [samzhang111/Friendship#4]
I'll be home after November 16th to what looks to be December 2nd. Maybe longer. Are you in town? Let's hang out then? (or if you come here outside of those times -- we can hang out then too)

Excuse the rooster emoji in the title -- the turkey emoji (🦃) is broken on my screen.

**Comment by mattwigway** [comment]
Yep! I am here for the duration exception November 25-29 (I'll be in Ohio for Thanksgiving).

**Comment by mattwigway** [comment]
We did this :)
